In [5]:
# data opration
import torch

In [6]:
# 创建一维张量
x = torch.arange(12)
y = torch.arange(1,4)
print(x)
y

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


tensor([1, 2, 3])

In [7]:
# 张量的形状
print(x.shape)
y.shape
# 形状： [3]
# 维度： 1维
# 元素个数：3

torch.Size([12])


torch.Size([3])

In [8]:
# 元素个数
x.numel()

12

In [9]:
# 改变形状函数reshape
x = x.reshape(3,4)
x
# 把原来 [12] 的一维张量，
# 变成了一个 3 行 × 4 列 的二维张量。

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
# 构造全0张量
torch.zeros((2,3,4))
# 它包含 2 个矩阵（最外层）；
# 每个矩阵有 3 行；
# 每行有 4 列；
# 所有数值都是 0.0

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
# 构造全1张量
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
# 通过提供包含数值的python列表（或嵌套列表）来为所需张量中的每个元素赋予确定值
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [13]:
# 通过提供包含数值的python列表（或嵌套列表）来为所需张量中的每个元素赋予确定值
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [16]:
# 常见标准算数运算符（+ - * / **幂运算）
x = torch.tensor([1.0,2,3,4])
y = torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([3., 4., 5., 6.]),
 tensor([-1.,  0.,  1.,  2.]),
 tensor([2., 4., 6., 8.]),
 tensor([0.5000, 1.0000, 1.5000, 2.0000]),
 tensor([ 1.,  4.,  9., 16.]))

In [17]:
# 将多个张量连结在一起
x = torch.arange(12, dtype=torch.float32).reshape(3,4)
# dtype=torch.float32就把所有元素都转换为32位浮点数tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 10., 11.])
y = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)
# torch.cat() 是 concatenate（拼接） 的缩写，用来在指定维度 dim 上连接两个（或多个）张量。
# 当 dim=0 时（按行拼接）
# 当 dim=1 时（按列拼接）

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [27]:
x = torch.zeros((2, 3, 4, 5))
# 四维(batch, channel, height, width)
x

tensor([[[[[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]]],


         [[[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]]]],



        [[[[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0.,

In [31]:
# 通过逻辑运算符构建二元张量
x = torch.arange(12, dtype=torch.float32).reshape(3,4)
y = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [32]:
# 对张量中的所有元素进行求和会产生一个只有一个元素的张量
x.sum()

tensor(66.)

In [37]:
# 通过广播机制来执行按照元素操作
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
print(a)
print(b)
a+b

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])


tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [38]:
x[-1],x[1:3]
# -1表示最后一行
# 1:3表示第一行到第二行

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [40]:
# 改写张量的值
x[1,2]=3
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  3.,  7.],
        [ 8.,  9., 10., 11.]])

In [41]:
# 多个元素的赋值
x[0:2, :]=1
# 从0行到第一行所有列的赋值
x

tensor([[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 8.,  9., 10., 11.]])

In [47]:
# 运行一些新操作可能会导致为结果分配内存
before = id(y)
# id() 是 Python 的内置函数，作用是返回对象在内存中的唯一标识（Identity）。
print(id(y))
print(before)
y = y + x
print(id(y))
print(before)
id(y) == before

134151093574048
134151093574048
134151093575968
134151093574048


False

In [50]:
# 执行原地操作
z = torch.zeros_like(y)
# 创建一个与张量 y 形状（shape）和数据类型（dtype）完全相同、但所有元素都为 0 的新张量。
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))
# 特别大的矩阵如果一直复制操作创造新的内存空间可能导致内存不够

id(z): 134151093021312
id(z): 134151093021312


In [51]:
# 如果在后续操作中没有重复使用x，也可以使用x[：] = x + y 或 x += y 来减少操作的内存开销
before =id(x)
x += y
id(x) == before


True

In [53]:
# 转换为numpy张量
# PyTorch 张量（Tensor）与 NumPy 数组（ndarray）之间的相互转换
A = x.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [55]:
# 将大小为1的张量转换为python标量

a = torch.tensor([3.5])
a, a.item(),float(a), int(a)
# .item() 用来从单元素张量中取出它的 Python 标量值。
# Python 看到一个单元素张量时，会尝试自动转换为浮点数。
# 同理，int() 也能把单元素张量转为整数（会向下取整）。

(tensor([3.5000]), 3.5, 3.5, 3)