<a href="https://colab.research.google.com/github/7ING-IC/Practice_DeepLearning/blob/main/linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
# 标量由只有一个元素的张量显示
x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x/y, x**y
# 返回的是一个元组

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [3]:
# 将向量视为标量值组成的列表
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [5]:
# 使用张量的索引来访问任一元素
x[3]

tensor(3)

In [7]:
# 张量的长度
len(x)

4

In [9]:
# 张量的形状
x.shape

torch.Size([4])

In [15]:
# 通过指定两个分量m和n来创建一个形状为m*n的矩阵
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [14]:
# 矩阵的转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [17]:
# 对称矩阵
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [20]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [23]:
# 给定具有相同形状的任何两个张量，任何按照元素二元运算结果的都将是相同形状的张量
A = torch.arange(20, dtype= torch.float32).reshape(5, 4)
B = A.clone()
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [25]:
# 哈达玛积
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [27]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [29]:
# 计算元素的和
A = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0, 1, 2, 3]), tensor(6))

In [37]:
# 表示任意形状张量的元素和
A = torch.arange(40).reshape(2, 5, 4)
A, A.shape, A.sum()

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]),
 torch.Size([2, 5, 4]),
 tensor(780))

In [34]:
# 指定求和汇总张量的轴
# 表示按第 0 维求和
A_sum_axis0= A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [38]:
A_sum_axis0= A.sum(axis=1)
A_sum_axis0, A_sum_axis0.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]))

In [41]:
A.sum(axis=[0, 1]).shape

torch.Size([4])

In [45]:
A = A.float()
# A.numel()是元素个数
A.mean(), A.sum() / A.numel()

(tensor(19.5000), tensor(19.5000))

In [53]:
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
# 计算总和或均值的时候保持轴数不变
sum_A = A.sum(axis=1, keepdims=True)
# keepdims=True让结果仍然保持原来的维度数量
sum_A, sum_A.shape

(tensor([[ 6],
         [15]]),
 torch.Size([2, 1]))

In [52]:
# 因为形状相同所以可以运算
A / sum_A

tensor([[0.1667, 0.3333, 0.5000],
        [0.2667, 0.3333, 0.4000]])

In [54]:
# 某个轴计算A元素的累积总和
A.cumsum(axis=0)

tensor([[1, 2, 3],
        [5, 7, 9]])

In [61]:
# 点积是相同位置的按元素乘积的和
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [64]:
# torch.mv(input, vec)
# matrix–vector乘法

In [69]:
A = torch.ones(3,4)
B = torch.ones(4,3)
torch.mm(A, B)
# matrix–matrix乘法

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])

In [71]:
# 计算向量元素和的平方根
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [73]:
# 计算向量元素的绝对值之和
torch.abs(u).sum()

tensor(7.)

In [74]:
# 矩阵的Frobenius norm是矩阵元素的平方和的平方根
torch.norm(torch.ones((4, 9)))

tensor(6.)